import api from '../api/axios';

/**
 * Upload Service
 * Handles Cloudinary signed uploads
 */

/**
 * Get signed upload parameters for profile picture
 * @returns {Promise<Object>} Upload signature data
 */
export const getProfileUploadSignature = async () => {
    const response = await api.post('/uploads/sign/profile');
    return response.data.data;
};

/**
 * Get signed upload parameters for product images
 * @returns {Promise<Object>} Upload signature data
 */
export const getProductUploadSignature = async () => {
    const response = await api.post('/uploads/sign/product');
    return response.data.data;
};

/**
 * Upload image to Cloudinary using signed upload
 * @param {File} file - The image file to upload
 * @param {Object} signatureData - Signature data from backend
 * @param {Function} onProgress - Progress callback (0-100)
 * @returns {Promise<Object>} Cloudinary upload response
 */
export const uploadToCloudinary = async (file, signatureData, onProgress) => {
    const formData = new FormData();
    formData.append('file', file);
    formData.append('api_key', signatureData.apiKey);
    formData.append('timestamp', signatureData.timestamp);
    formData.append('signature', signatureData.signature);
    formData.append('folder', signatureData.folder);
    formData.append('eager', signatureData.eager);
    if (signatureData.allowedFormats) {
        formData.append('allowed_formats', signatureData.allowedFormats);
    }
    // Security: Bind upload to the specific public_id generated by backend
    if (signatureData.publicId) {
        formData.append('public_id', signatureData.publicId);
    }
    // Security: Pass the signed transformation
    if (signatureData.transformation) {
        formData.append('transformation', signatureData.transformation);
    }

    const resourceType = signatureData.resourceType || 'image';
    const cloudinaryUrl = `https://api.cloudinary.com/v1_1/${signatureData.cloudName}/${resourceType}/upload`;

    return new Promise((resolve, reject) => {
        const xhr = new XMLHttpRequest();

        xhr.upload.addEventListener('progress', (event) => {
            if (event.lengthComputable && onProgress) {
                const percentComplete = Math.round((event.loaded / event.total) * 100);
                onProgress(percentComplete);
            }
        });

        xhr.addEventListener('load', () => {
            if (xhr.status >= 200 && xhr.status < 300) {
                const result = JSON.parse(xhr.responseText);
                resolve({
                    url: result.secure_url,
                    publicId: result.public_id,
                    width: result.width,
                    height: result.height,
                    format: result.format,
                    eager: result.eager, // Contains transformed versions
                });
            } else {
                reject(new Error(`Upload failed: ${xhr.statusText}`));
            }
        });

        xhr.addEventListener('error', () => {
            reject(new Error('Upload failed'));
        });

        xhr.open('POST', cloudinaryUrl);
        xhr.send(formData);
    });
};

/**
 * Upload profile picture (convenience function)
 * @param {File} file - The image file
 * @param {Function} onProgress - Progress callback
 * @returns {Promise<Object>} Upload result with url and publicId
 */
export const uploadProfilePicture = async (file, onProgress) => {
    const signatureData = await getProfileUploadSignature();
    return uploadToCloudinary(file, signatureData, onProgress);
};

/**
 * Upload product image (convenience function)
 * @param {File} file - The image file
 * @param {Function} onProgress - Progress callback
 * @returns {Promise<Object>} Upload result with url and publicId
 */
export const uploadProductImage = async (file, onProgress) => {
    const signatureData = await getProductUploadSignature();
    return uploadToCloudinary(file, signatureData, onProgress);
};

/**
 * Update user profile picture in the database
 * @param {string} userId - User ID
 * @param {Object} imageData - { url, publicId }
 * @returns {Promise<Object>} Updated user data
 */
export const updateUserProfilePicture = async (userId, imageData) => {
    const response = await api.put(`/users/${userId}/profile-picture`, imageData);
    return response.data.data;
};

/**
 * Delete profile picture from Cloudinary
 * @param {Object} imageData - { imageUrl } or { publicId }
 * @returns {Promise<Object>} Deletion result
 */
export const deleteProfilePicture = async (imageData) => {
    const response = await api.delete('/uploads/delete-profile', { data: imageData });
    return response.data;
};

/**
 * Delete product image from Cloudinary (admin only)
 * @param {Object} imageData - { imageUrl } or { publicId }
 * @returns {Promise<Object>} Deletion result
 */
export const deleteProductImage = async (imageData) => {
    const response = await api.delete('/uploads/delete', { data: imageData });
    return response.data;
};
